apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegram-drawer
  namespace: beta-parrot-bot
  labels:
    app: telegram-drawer
spec:
  selector:
    matchLabels:
      app: telegram-drawer
  replicas: 1
  template:
    metadata:
      labels:
        app: telegram-drawer
    spec:
      imagePullSecrets:
        - name: docker-pass
      containers:
        - name: telegram-drawer
          image: ghcr.io/danilandreev/github-parrot-bot-dev
          ports:
            - containerPort: 3100
          volumeMounts:
            - mountPath: /.env
              subPath: .env
              name: env
      volumes:
        - name: env
          configMap:
            name: telegram-drawer
            items:
              - key: env
                path: .env