name: ESLint code check

on:
  pull_request:
    branches: [ master ]

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2      
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: "Setup eslint package."
        run: npm install -g eslint
      - name: "Setup eslint plugin: typescript-eslint/eslint-plugin."
        run: npm install @typescript-eslint/eslint-plugin --dev
      - name: "Setup eslint plugin: @typescript-eslint/parser."
        run: npm install @typescript-eslint/parser --dev
      - name: Run ESLint check.
        run: eslint ./src
        
