name: Publish docker image to dev registry

on:
  push:
    branches: [ master ]

jobs:
  ghcr:
    runs-on:
      - skaffold
    steps:
      - uses: actions/checkout@v2
      - name: Run Skaffold build and publish.
        run: skaffold run -p beta
