name: Unit testing | autotests

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: "Jest"
    steps:
      - uses: actions/checkout@v2      
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Run yarn froze lockfile
        run: yarn --frozen-lockfile
      - name: Install dependencies
        run: yarn install
      - name: Run test suits
        run: yarn run test
